version: '3.4'

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgresdb;Database=postgres;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    command: bash -c "dotnet LearningCourses.dll"

volumes:
  postgres_data: